---
title: "OWI a-la-carte March 10, 2016 agenda"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      out_dir <- 'test';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file='../index.html') })
output: markdowntemplates::skeleton
---

##USGS OWI workshop: Tools for access, manipulation, and modeling of federal water and climate data


|  Schedule (CST) | Task / Module  | Tools(s)  | System-specific?  | Lead  |   
|---|---|---|---|---|
|  9-10am | [Introduction and Reproducibility](http://usgs-r.github.io/a-la-carte/best_practices.html)  | R  | No  | [Alison Appling](http://cida.usgs.gov/people/aappling.html) |   
|  10-10:45am | [Access federal water data](http://usgs-r.github.io/a-la-carte/dataRetrieval.html)  | [dataRetrieval](https://cran.r-project.org/web/packages/dataRetrieval/index.html)  | No | [Laura DeCicco](http://cida.usgs.gov/people/ldecicco.html)  |   
|  10:45-11am | Break  |   |   |   |   
|  11-11:30am | [Access fed. water data, con't](http://usgs-r.github.io/a-la-carte/dataRetrieval.html)  |   |   |   |   
|  11:30-12:30pm | [Access climate and land use data](http://usgs-r.github.io/a-la-carte/geoknife.html)  | [geoknife](https://cran.r-project.org/web/packages/geoknife/index.html)  | No  | [Jordan Read](http://cida.usgs.gov/people/jread.html), [Jordan Walker](http://cida.usgs.gov/people/jiwalker.html) |   
|  12:30-1:30pm | Lunch  |   |   |   |   
|  1:30-2pm | [NHD/NHD+](http://usgs-r.github.io/a-la-carte/nhd_plus.html) | ad hoc  | No  | [Emily Read](http://cida.usgs.gov/people/eread.html), [Dave Blodgett](http://cida.usgs.gov/people/dblodgett.html)  |   
|  2-2:30pm | Estimate constituent loading to streams / lakes  | [rLoadest](https://github.com/USGS-R/rloadest), [WRTDS](https://cran.r-project.org/web/packages/EGRET/index.html)  | No  | [Laura DeCicco](http://cida.usgs.gov/people/ldecicco.html)  |   
|  2:30-2:45pm | Break  |   |   |   |   
|  2:45-3:45pm | [Hydrodynamic modeling with GLM](http://usgs-r.github.io/a-la-carte/glmtools.html)  | GLM, [GLMr](https://github.com/GLEON/GLMr), [glmtools](https://github.com/USGS-R/glmtools)  | Lake  | [Jordan Read](http://cida.usgs.gov/people/jread.html), [Luke Winslow](http://cida.usgs.gov/people/lwinslow.html)  |   
|  3:45-4:15pm | Distributing computing  | [HTCondor](https://research.cs.wisc.edu/htcondor/)  | No  | [Luke Winslow](http://cida.usgs.gov/people/lwinslow.html) |   
|  4:15-4:45pm | Final discussion and wrap up  |   |   |   |  

###For remote participants
####Webex
Thursday, March 10, 2016 | 8:45 am Central Standard Time (GMT-06:00) 
Meeting number: 712 525 502
[Meeting link](https://usgs.webex.com/usgs/j.php?MTID=m42216ab885b59e2e5f84c155d69c7e7e)

####Audio connection
At start time of the conference, each location must call: 703-648-4848.  Refer to invitation email sent 3/9/2016 email for audio access code.

